server {
    listen 80;
    listen [::]:80;
    server_name status.loutik.fr;

    # Redirection globale vers HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name status.loutik.fr;
    http2 on;

    ssl_certificate /etc/letsencrypt/live/loutik.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/loutik.fr/privkey.pem;

    include /etc/nginx/snippets/error_pages.conf;

    location = /favicon.ico {
        alias /var/www/html/assets/logo_loutik-health.png;
        access_log off;
        log_not_found off;
    }

    location / {
        proxy_pass http://localhost:1025;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;    
    }
}